// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "username": "nisse",
  "email": "nisse@mail.com",
  "password": "test"
}

###

// HÄMTA ALLA ANVÄNDARE
GET http://localhost:3000/api/users/

###

// SKAPA NY POST
POST http://localhost:3000/api/posts/add
Content-Type: application/json

{
  "title": "Måndag",
  "content": "Sol",
  "userId": "64636ed4029c2eb1613b2f5e"
}

###
// LOGGA IN ANVÄNDARE
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
"email": "Sebbe9@mail.com", "password": "Sebastian"
}

###

GET http://localhost:3000/api/posts


###

// HÄMTA SPECIFIK ANVÄNDARE
POST http://localhost:3000/api/users
Content-Type: application/json

{
"_id": "64636ed4029c2eb1613b2f5e"
}

###

// HÄMTA SPECIFIK POST
POST http://localhost:3000/api/posts
Content-Type: application/json

{
"_id": "646bdfc5d81ee0acc9be8e15"
}

###

//DELETE POST
DELETE http://localhost:3000/api/posts/delete
Content-Type: application/json

{
  "_id": "646c6991bcef05a02df31d45"
}

###
//UPPDATERA POST
PUT http://localhost:3000/api/posts/646bdfc5d81ee0acc9be8e15
Content-Type: application/json

{
  "title": "Blir det ändring igeeeen?",
  "content": "FUUUUUUNGERA!!!!"
  
}