// SKAPA USER // LÖSENORD SKALL KRYPTERAS FÖR VG ✅
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "username": "Felix Anneblad",
  "email": "anneblad89@mail.com",
  "password": "Felix"
}

###

// HÄMTA ALLA ANVÄNDARE

POST http://localhost:3000/api/posts/add
Content-Type: application/json

{
  "title": "Felix Anneblad add post 2",
  "content": "Felix Anneblad have added a post 2 ",
  "author": "Felix Anneblad"
}

###>>>>>>> main
GET http://localhost:3000/api/users

###
// LOGGA IN ANVÄNDARE
POST http://localhost:3000/api/users/login 
Content-Type: application/json

{
"email": "anneblad89@mail.com", "password": "Felix"
}